# Generated by Django 4.2.11 on 2026-03-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn thanh toán VietQR'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Mã thanh toán VietQR'),
        ),
    ]
