# Generated by Django 4.2.11 on 2026-03-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_order_payment_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Chờ thanh toán'), ('pending', 'Đã đặt hàng'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Hủy đơn'), ('payment_expired', 'Hết hạn thanh toán')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
