# Generated by Django 4.2.11 on 2026-03-23 03:11

from django.db import migrations, models


def backfill_payment_status(apps, schema_editor):
    """
    Điền payment_status cho dữ liệu cũ dựa theo order.status hiện tại:
    - delivered / processing / shipped  → paid      (đã thanh toán)
    - payment_expired                   → expired   (hết hạn VietQR)
    - cancelled                         → cancelled (đã hủy)
    - pending / awaiting_payment        → pending   (mặc định, không đổi)
    """
    Order = apps.get_model('store', 'Order')
    Order.objects.filter(status__in=['processing', 'shipped', 'delivered']).update(payment_status='paid')
    Order.objects.filter(status='payment_expired').update(payment_status='expired')
    Order.objects.filter(status='cancelled').update(payment_status='cancelled')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_order_add_payment_expired_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy thanh toán'), ('expired', 'Hết hạn thanh toán')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.RunPython(backfill_payment_status, migrations.RunPython.noop),
    ]
